version: 2

sources:
  - name: raw_healthcare
    description: "Raw healthcare data from source systems"
    database: healthcare_raw
    schema: public
    tables:
      - name: raw_patients
        description: "Patient demographic information"
        columns:
          - name: patient_id
            description: "Unique patient identifier"
            tests:
              - unique
              - not_null
      
      - name: raw_encounters
        description: "Patient hospital encounters"
        columns:
          - name: encounter_id
            tests:
              - unique
              - not_null
      
      - name: raw_claims
        description: "Billing claims"
        columns:
          - name: claim_id
            tests:
              - unique
              - not_null
      
      - name: raw_providers
        description: "Healthcare provider information"
        columns:
          - name: provider_id
            tests:
              - unique
              - not_null